FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY index.html .
COPY tsconfig.json tsconfig.node.json vite.config.ts eslint.config.js ./
COPY src ./src

EXPOSE 5173

CMD ["npm", "run", "dev"]

